### ISSUE TITLE
Solution for the example in 1.1

### ISSUE THREAD

**Issue by unfode** [ocaml-multicore/ocaml-effects-tutorial#11]
Adding a function `run` should suffice. No need to modify `sum_up`.
```ocaml
exception Conversion_failure of string

let int_of_string l =
  try int_of_string l with
  | Failure _ -> raise (Conversion_failure l)

let rec sum_up acc =
    let l = input_line stdin in
    acc := !acc + int_of_string l;
    sum_up acc

let rec run (acc: int ref) = (
  try sum_up acc with
  | End_of_file -> Printf.printf "Sum is %d\n" !acc
  | Conversion_failure s ->
    (Printf.fprintf stderr "Conversion failure \"%s\"\n%!" s; run acc)
)

let () =
  let r = ref 0 in
  run r
```

**Comment by dhil** [comment]
There's more than one way to peel an orange. 

But this solution is missing the point of the exercise. The point is to get familiar with capturing and resuming continuations with effect handlers.

**Comment by unfode** [comment]
My point is, it would be nice if the introductory example cannot be solved elegantly without effects, convincing readers that effects are necessary. But apparently it's not the case for the current introductory example.
